### ISSUE TITLE
Nick is Slacking

### ISSUE THREAD

**Issue by JackFratto** [Chronomaton/ProjectRedPanda#1]
Project founder drafted the vision for a wildly successful game that would net $1,000,000 in revenue every Monday; however, team member Nick isn't doing his part by implementing the "New Game" mechanics.

**Comment by Chronomaton** [comment]
I completely agree. The multi-million dollar genre-transforming game is already behind schedule primarily due to Nick. He WILL be disciplined...

**Comment by Chronomaton** [comment]
Nick has not responded to any discipline. In fact, not only has he not completed his small assigned portion, he has deleted all other work up to this point. Issue reopened. This should be elementary.
